### PR TITLE
fixed utf8 issue

### PR DESCRIPTION
**Pull request by Vishal-Padia**
migrating code via windows machine gave out an utf8 encoding error. Fixed it in the helpers.py
image

### CODE REVIEW

**Comment by govindansriram** [comment]
In relation to issue #53, I believe this error is caused because of the `npz` file type. According to Numpy [documentation](https://numpy.org/doc/stable/reference/generated/numpy.load.html), this is the recommended way to deal with context management of a `npz` File. 

______
If the file is a .npz file, the returned value supports the context manager protocol in a similar fashion to the open function:

```python
with load('foo.npz') as data:
    a = data['a']
```
The underlying file descriptor is closed when exiting the `with` block.
________

In the current way we do this, we never close the file. Hence when the IterableChunker proceeds to delete the file, a process error is thrown by Windows since the file is still open.

To fix this issue we need to add the `with` statement to the `NumpyFile` class in file_saver.py. The method should look like this:

```python 
NumpyFile(BaseFile):
   ...
   @classmethod
    def load(cls, save_path: str, enforce_shape: bool):
        instance = cls(enforce_shape)

        if enforce_shape:
            instance.arr = np.load(save_path, allow_pickle=True)
        else:
            with load(save_dict) as loaded_array:
                instance.arr_dict = loaded_array

        return instance
```

**Comment by Vishal-Padia** [comment]
I have added `with` statement and yeah it should be used with numpy.load instead of load.
`np.load` with the `with` statement to ensure proper file closure.

**Comment by govindansriram** [comment]
> I have added `with` statement and yeah it should be used with numpy.load instead of load.
> 
> `np.load` with the `with` statement to ensure proper file closure.

Did the tests pass?

**Comment by Vishal-Padia** [comment]
Okay the tests are running now
Will update you it anything goes wrong.

**Comment by Vishal-Padia** [comment]
One of the tests failed, looking into it.

**Comment by govindansriram** [comment]
Can you send the error?

**Comment by Vishal-Padia** [comment]
====================================================== FAILURES =======================================================
________________________________________________ test_all_file_savers _________________________________________________

    def test_all_file_savers():
>       all_file_savers()

tests\data\test_filesavers.py:246:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\data\test_filesavers.py:225: in all_file_savers
    for _ in tqdm(dl):
.nox\tests-3-11\Lib\site-packages\tqdm\std.py:1182: in __iter__
    for obj in iterable:
.nox\tests-3-11\Lib\site-packages\torch\utils\data\dataloader.py:633: in __next__
    data = self._next_data()
.nox\tests-3-11\Lib\site-packages\torch\utils\data\dataloader.py:677: in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
.nox\tests-3-11\Lib\site-packages\torch\utils\data\_utils\fetch.py:32: in fetch
    data.append(next(self.dataset_iter))
.nox\tests-3-11\Lib\site-packages\benchkit\data\datasets.py:274: in _data_iterator
    yield self.unpack_data(index)
tests\data\test_filesavers.py:187: in unpack_data
    number, np1, np2, b1, t1, pt1, j1, r1 = super().unpack_data(idx)
.nox\tests-3-11\Lib\site-packages\benchkit\data\datasets.py:237: in unpack_data
    (*[i(idx) for i in self.file_converters],)
.nox\tests-3-11\Lib\site-packages\benchkit\data\datasets.py:237: in <listcomp>
    (*[i(idx) for i in self.file_converters],)
.nox\tests-3-11\Lib\site-packages\benchkit\data\file_saver.py:176: in __call__
    return self.arr_dict[f"np-{idx}"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = NpzFile 'object' with keys: np-0, np-1, np-2, np-3, np-4..., key = 'np-0.npy'

    def __getitem__(self, key):
        # FIXME: This seems like it will copy strings around
        #   more than is strictly necessary.  The zipfile
        #   will read the string and then
        #   the format.read_array will copy the string
        #   to another place in memory.
        #   It would be better if the zipfile could read
        #   (or at least uncompress) the data
        #   directly into the array memory.
        member = False
        if key in self._files:
            member = True
        elif key in self.files:
            member = True
            key += '.npy'
        if member:
>           bytes = self.zip.open(key)
E           AttributeError: 'NoneType' object has no attribute 'open'

.nox\tests-3-11\Lib\site-packages\numpy\lib\npyio.py:251: AttributeError

**Comment by govindansriram** [comment]
can you do allow_pickle = True?

**Comment by Vishal-Padia** [comment]
where do put it?

**Comment by govindansriram** [comment]
in load

**Comment by Vishal-Padia** [comment]
image
As you can see I have made that change and committed it an hour ago
but the tests failed

**Comment by Vishal-Padia** [comment]
Added it 
Now running tests

**Comment by Vishal-Padia** [comment]
Its still giving the same error

**Comment by govindansriram** [comment]
ok let me look into it more

**Comment by Vishal-Padia** [comment]
okay cool

**Comment by govindansriram** [comment]
The reason why we are getting the latest issues is because npz reads arrays using lazy loading. This means when you access an array the file cannot be closed. The conundrum however is the file needs to be closed in order for it to be safely deleted. The best intermediary solution is to close the file when the last needed array is read. Hence the newly added `_seen_count` and `_npz_key_count` instance variables.

Please change the NumpyFile Class to look like such.

-----
```python
class NumpyFile(BaseFile):
    def __init__(self, enforce_shape: bool, shape: tuple[int, ...] | None = None):
        super().__init__()
        self._enforce_shape = enforce_shape

        file_str = super().file_name
        file_str += "-{}"

        self._file_name = (
            file_str.format("enforced-array.npy")
            if enforce_shape
            else file_str.format("array.npz")
        )
        self.shape = shape

        self._arr_dict = {}
        self._npz_key_count = 0
        self._seen_count = 0
        self.arr = np.array([np.NaN])

    def reset(self):
        super().reset()
        file_str = super().file_name
        file_str += "-{}"
        self._file_name = (
            file_str.format("enforced-array.npy")
            if self.enforce_shape
            else file_str.format("array.npz")
        )
        self.arr_dict = {}
        self.arr = np.array([np.NaN])
        self.npz_key_count = 0
        self.seen_count = 0

    @property
    def seen_count(self):
        return self._seen_count

    @seen_count.setter
    def seen_count(self, seen_count):
        self._seen_count = seen_count

    @property
    def npz_key_count(self):
        return self._npz_key_count

    @npz_key_count.setter
    def npz_key_count(self, npz_key_count):
        self._npz_key_count = npz_key_count

    @property
    def arr_dict(self):
        return self._arr_dict

    @arr_dict.setter
    def arr_dict(self, arr_dict):
        self._arr_dict = arr_dict

    @property
    def arr(self):
        return self._arr

    @arr.setter
    def arr(self, arr):
        self._arr = arr

    @property
    def enforce_shape(self):
        return self._enforce_shape

    @enforce_shape.setter
    def enforce_shape(self, new_shape: tuple[int]):
        self._enforce_shape = new_shape

    def append(self, arr):
        if isinstance(arr, list):
            arr = np.array(arr)

        if self.enforce_shape:
            if arr.shape != self.shape:
                raise RuntimeError(
                    f"Enforced Shape of {self.shape} does not match array shape {arr.shape}"
                )

            arr = np.expand_dims(arr, axis=0)

            if np.isnan(self.arr).any():
                self.arr = arr
            else:
                self.arr = np.concatenate([self.arr, arr], axis=0)
        else:
            self.arr_dict[f"np-{len(self.arr_dict)}"] = arr

    def __call__(self, idx, *args, **kwargs):
        if self.enforce_shape:
            return self.arr[idx]
        else:
            self.seen_count += 1
            ret_arr = self.arr_dict[f"np-{idx}"]
            if self.npz_key_count == self.seen_count:
                self.arr_dict.close()
            return ret_arr

    @classmethod
    def load(cls, save_path: str, enforce_shape: bool):
        instance = cls(enforce_shape)

        loaded_array = np.load(save_path, allow_pickle=True)

        if enforce_shape:
            instance.arr = loaded_array
        else:
            instance.arr_dict = loaded_array
            instance.npz_key_count = len(loaded_array.keys())

        return instance

    def save(self):
        if self.enforce_shape:
            np.save(self.save_path, self.arr)

            return self.file_name, "enforced_arr"
        else:
            np.savez(self.save_path, **self.arr_dict)
            return self.file_name, "arr"
```

**Comment by govindansriram** [comment]
Please let me know if the tests succeed after this

**Comment by Vishal-Padia** [comment]
The tests are passed with 4 warnings.

**Comment by Vishal-Padia** [comment]
should I push it?

**Comment by Vishal-Padia** [comment]
All tests passed with 4 warnings and I have pushed the code please review it.

**Comment by govindansriram** [comment]
ok ill review

**Pull request merged**
